### ISSUE TITLE
Challenge #5 The Rewarder, ERC20Snapshot.sol no longer available in OpenZeppelin v5.0.0

### ISSUE THREAD

**Issue by alexbabits** [theredguild/damn-vulnerable-defi#46]
OpenZeppelin got rid of their `ERC20Snapshot.sol` contract in the `v5.0.0` upgrades, so I am having trouble compiling challenge 5 The Rewarder with the `AccountingToken.sol`. I am using Foundry. Perhaps it is specific to Foundry.

I tried to place the missing dependencies into my v5.0.0 `lib`. The `ERC20Snapshot.sol` from v4.9.3, along with its missing dependency `Counters.sol` from v4.9.3. `Arrays.sol` is already in v5.0.0. But this did not work and I was getting errors regarding functions not being correct and stuff like that. I'm unsure how to contend with a missing OZ dependency. Would installing the entire v4.9.3 OZ library maybe work? Or another version? I would prefer not to if possible since I'm trying to house all the challenges in one repo.

See the 2 pictures for specific errors. The first picture says ERC20 was not found because `AccountingToken.sol` doesn't have ERC20 import. Therefore I tried importing ERC20 as well, but then it complained about the ERC20Snapshot functions.

*Edit: Challenge 6 Selfie and potentially any others that use `DamnValuableTokenSnapshot.sol` or `ERC20Snapshot.sol` dependency from Open Zeppelin will need a remedy?

![1](https://github.com/tinchoabbate/damn-vulnerable-defi/assets/102264368/890bafb3-8c56-4594-a655-ca8f2ee39cb4)
![2](https://github.com/tinchoabbate/damn-vulnerable-defi/assets/102264368/e1259b97-7a61-48ea-83af-0307f184f35d)

**Comment by perplexedpigmy** [comment]
Why not just install the version that contains the missing contract
```
forge install OpenZeppelin/openzeppelin-contracts@release-v4.9 
```
