### ISSUE TITLE
Unused variable 'address monitor' in UnstoppableChallenge.t.sol

### ISSUE THREAD

**Issue by NFTMerchant** [theredguild/damn-vulnerable-defi#76]
In the UnstoppableChallenge.t.sol file, the variable address monitor = makeAddr("monitor"); is declared but never used

**Comment by tinchoabbate** [comment]
thanks, fixed in [d7ee293](https://github.com/theredguild/damn-vulnerable-defi/commit/d7ee29322fdfd746c697dcf01115147652f0a4ee)
